package com.example.mine.mapper;

import com.example.mine.entity.Image;
import com.example.mine.entity.ImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    long countByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    int deleteByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    int insert(Image row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    int insertSelective(Image row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    List<Image> selectByExample(ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Image row, @Param("example") ImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.image
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Image row, @Param("example") ImageExample example);
}