package com.example.mine.mapper;

import com.example.mine.entity.Ingredient;
import com.example.mine.entity.IngredientExample;
import com.example.mine.entity.IngredientKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface IngredientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    long countByExample(IngredientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int deleteByExample(IngredientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(IngredientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int insert(Ingredient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int insertSelective(Ingredient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    List<Ingredient> selectByExample(IngredientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    Ingredient selectByPrimaryKey(IngredientKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Ingredient row, @Param("example") IngredientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Ingredient row, @Param("example") IngredientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Ingredient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ingredient
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Ingredient row);
}