package com.example.mine.mapper;

import com.example.mine.entity.Recipe;
import com.example.mine.entity.RecipeExample;
import com.example.mine.entity.RecipeKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface RecipeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    long countByExample(RecipeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int deleteByExample(RecipeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RecipeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int insert(Recipe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int insertSelective(Recipe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    List<Recipe> selectByExample(RecipeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    Recipe selectByPrimaryKey(RecipeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Recipe row, @Param("example") RecipeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Recipe row, @Param("example") RecipeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Recipe row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.recipe
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recipe row);
}