package com.example.mine.mapper;

import com.example.mine.entity.Tag;
import com.example.mine.entity.TagExample;
import com.example.mine.entity.TagKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int insert(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int insertSelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    List<Tag> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    Tag selectByPrimaryKey(TagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Tag row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tag row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.tag
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tag row);
}