package com.example.mine.entity;

import java.util.Date;

public class Image extends ImageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.image.recipe_id
     *
     * @mbg.generated
     */
    private Integer recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.image.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.image.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.image.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.image.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.image.recipe_id
     *
     * @return the value of public.image.recipe_id
     *
     * @mbg.generated
     */
    public Integer getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.image.recipe_id
     *
     * @param recipeId the value for public.image.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.image.path
     *
     * @return the value of public.image.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.image.path
     *
     * @param path the value for public.image.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.image.file_name
     *
     * @return the value of public.image.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.image.file_name
     *
     * @param fileName the value for public.image.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.image.created_by
     *
     * @return the value of public.image.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.image.created_by
     *
     * @param createdBy the value for public.image.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.image.created_at
     *
     * @return the value of public.image.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.image.created_at
     *
     * @param createdAt the value for public.image.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
}