package com.example.mine.entity;

public class RecipeTagLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.recipe_tag_link.recipe_id
     *
     * @mbg.generated
     */
    private Integer recipeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.recipe_tag_link.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.recipe_tag_link.recipe_id
     *
     * @return the value of public.recipe_tag_link.recipe_id
     *
     * @mbg.generated
     */
    public Integer getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.recipe_tag_link.recipe_id
     *
     * @param recipeId the value for public.recipe_tag_link.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.recipe_tag_link.tag_id
     *
     * @return the value of public.recipe_tag_link.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.recipe_tag_link.tag_id
     *
     * @param tagId the value for public.recipe_tag_link.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}