package com.example.mine.entity;

public class RecipeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.recipe.recipe_id
     *
     * @mbg.generated
     */
    private Integer recipeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.recipe.recipe_id
     *
     * @return the value of public.recipe.recipe_id
     *
     * @mbg.generated
     */
    public Integer getRecipeId() {
        return recipeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.recipe.recipe_id
     *
     * @param recipeId the value for public.recipe.recipe_id
     *
     * @mbg.generated
     */
    public void setRecipeId(Integer recipeId) {
        this.recipeId = recipeId;
    }
}