package com.example.mine.entity;

public class TagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.tag.tag_id
     *
     * @mbg.generated
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.tag.tag_id
     *
     * @return the value of public.tag.tag_id
     *
     * @mbg.generated
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.tag.tag_id
     *
     * @param tagId the value for public.tag.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}